#!/usr/bin/env python3
# atrium --dump-schema on stdin → C++ that only marks the strings for lupdate
# (QT_TRANSLATE_NOOP, context "settings"); it's never compiled.
import json, re, sys

# As SettingsPages::choiceOptions labels a choice.
NAMES = {"duckduckgo": "DuckDuckGo", "centered": "Centred", "brave": "Brave Search"}

def choice_label(c):
    if c in NAMES:
        return NAMES[c]
    return " ".join(w[:1].upper() + w[1:] for w in re.split(r"[-_]", c) if w)

def quote(s):
    return json.dumps(s, ensure_ascii=False)

schema = json.load(sys.stdin)
seen = []
def add(s):
    if s and s not in seen:
        seen.append(s)
for s in schema:
    add(s["page"])
    add(s["title"])
    add(s["description"])
    for c in s.get("choices") or []:
        add(choice_label(c))
print("// Generated by translations/update.sh from atrium --dump-schema: Settings'")
print("// texts, which the shell translates with qsTranslate(\"settings\", ...).")
print("// For lupdate only; never compiled.")
print("static const char* const settings_strings[] = {")
for s in seen:
    print(f'    QT_TRANSLATE_NOOP("settings", {quote(s)}),')
print("};")
